spring.application.name=metasync

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.multiTenancy=SCHEMA
spring.jpa.hibernate.ddl-auto=none

spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}

spring.liquibase.parameters.POSTGRES_USER=${POSTGRES_USER}

resend.api-key=${RESEND_API_KEY}
resend.from=${APP_EMAIL_FROM}

spring.freemarker.template-loader-path=classpath:/templates/email/
